{{- if and .Values.networkPolicy.enabled (ne .Values.database.type "external") }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "terminal.mariadb.fullname" . }}
  labels:
    {{- include "terminal.mariadb.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- if eq .Values.database.type "internal" }}
      {{- include "terminal.mariadb.selectorLabels" . | nindent 6 }}
      {{- else if eq .Values.database.type "operator" }}
      app.kubernetes.io/name: mariadb
      app.kubernetes.io/instance: {{ include "terminal.mariadb.fullname" . }}
      {{- end }}
  policyTypes:
    - Ingress
  ingress:
    # Allow connections from the web application
    - from:
        - podSelector:
            matchLabels:
              {{- include "terminal.web.selectorLabels" . | nindent 14 }}
      ports:
        - protocol: TCP
          port: 3306
    # Allow connections from the database cleanup cronjob
    - from:
        - podSelector:
            matchLabels:
              {{- include "terminal.databaseCleanup.selectorLabels" . | nindent 14 }}
      ports:
        - protocol: TCP
          port: 3306
{{- end }}
