{{- if eq .Values.database.type "internal" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "terminal.mariadb.fullname" . }}
  labels:
    {{- include "terminal.mariadb.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.database.port }}
      targetPort: mariadb
      protocol: TCP
      name: mariadb
  selector:
    {{- include "terminal.mariadb.selectorLabels" . | nindent 4 }}
{{- end }}
