{{- /* Secret is needed for all database types to store credentials */ -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "terminal.mariadb.secretFullname" . }}
  labels:
    {{- include "terminal.mariadb.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- include "terminal.env.mariadb.secret.data" . | nindent 2 }}
