apiVersion: v1
kind: Secret
metadata:
  name: {{ include "terminal.secret.fullname" . }}
  labels:
    {{- include "terminal.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- include "terminal.env.auth.secret.data" . | nindent 2 }}
  {{- include "terminal.env.mailer.secret.data" . | nindent 2 }}
