{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "terminal.web.fullname" . }}
  labels:
    {{- include "terminal.web.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "terminal.web.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    # Allow ingress traffic from any source
    - ports:
        - protocol: TCP
          port: {{ .Values.web.service.port }}
{{- end }}
